### ISSUE TITLE
How to use it? I had download and run in VSCode

### ISSUE THREAD

**Issue by vulieumang** [decodedhealth/flutter_zoom_plugin#12]
Hello, 
How to use it? I had download and run in VSCode
about 2 project main and example
Main
![image](https://user-images.githubusercontent.com/13487753/76384350-2d525680-6391-11ea-9188-83c7465f2465.png)
Example
![image](https://user-images.githubusercontent.com/13487753/76384413-5c68c800-6391-11ea-9f46-42cd644cf12a.png)

Please help to run it

**Comment by DzungTNgo** [comment]
Hi,

I am not sure what issue you are having here.
Please make sure you have followed the instructions to set up flutter and your IDE on your device here [https://flutter.dev/docs/get-started/install/macos](https://flutter.dev/docs/get-started/install/macos).
You should be able to run the example after setting up flutter correctly.

Cheers,

**Comment by vulieumang** [comment]
> Hi,
> 
> I am not sure what issue you are having here.
> Please make sure you have followed the instructions to set up flutter and your IDE on your device here https://flutter.dev/docs/get-started/install/macos.
> You should be able to run the example after setting up flutter correctly.
> 
> Cheers,

Thank you, I mean, When I download the package and run example it have error and I had screenshot it.
I had build some app flutter before.
Are you run success example is this package, if success what step you do?

**Comment by DzungTNgo** [comment]
The example can be started by running the `example/lib/main.dart`.
Please make sure that you are using the `master_dev` branch if you are testing with the simulator. You will also need a Zoom API key/secret pair to test it.

I can see also there is the error `Linker Command failed with exit code 1 (use -v to see invocation)`. Please check the log to see what causes that issue.

**Comment by vulieumang** [comment]
Thank you DzungTNgo,
I had success run it.
For iOS dev:
I only run on real device, not simulator, and need add permission for camera, audio and internet, config team on xcode.
![image](https://user-images.githubusercontent.com/13487753/76604578-8eb92780-6541-11ea-90a2-1ddeba92cbe9.png)

Android is can run normal.
Remember put key and secret key in meeting_screen.dart
![image](https://user-images.githubusercontent.com/13487753/76604642-b3150400-6541-11ea-9576-5da4fe46ef94.png)

**Comment by salahturkmen** [comment]
> 
> 
> Thank you DzungTNgo,
> I had success run it.
> For iOS dev:
> I only run on real device, not simulator, and need add permission for camera, audio and internet, config team on xcode.
> ![image](https://user-images.githubusercontent.com/13487753/76604578-8eb92780-6541-11ea-90a2-1ddeba92cbe9.png)
> 
> Android is can run normal.
> Remember put key and secret key in meeting_screen.dart
> ![image](https://user-images.githubusercontent.com/13487753/76604642-b3150400-6541-11ea-9576-5da4fe46ef94.png)

Sir, can you share the project without a api keys?

**Comment by aniteshreddy** [comment]
@vulieumang can you please send ur code . I have a trouble in getting started
