### ISSUE TITLE
How to build on emulator iOS, ignore this plugin

### ISSUE THREAD

**Issue by vulieumang** [decodedhealth/flutter_zoom_plugin#15]
Hi,
I had build and run on iOS real device, both android emulator and real device.
But I want test my app on iOS emulator for other function in app, and if I had embed this plugin, I can not build on emulator.
Anybody I know the way to ignore if I build on emulator iOS, and still run if I move to real device or Android.
It important with me, really thank too much if anybody can help!

**Comment by kevinbayes** [comment]
@vulieumang thanks for trying it out. 

When adding the dependency for iOS using the emulator did you ensure the plugin was 'master_dev' branch?
