### ISSUE TITLE
HELP, dont working on ANDROID release mode

### ISSUE THREAD

**Issue by cacianokroth** [decodedhealth/flutter_zoom_plugin#17]
- When I make a release build with zoom in on the app, it crashes the application when opens a zoom widget.
(I believe it is happening when generated in release mode.)

**Comment by cacianokroth** [comment]
Add guards, resolve this:
https://github.com/zoom/zoom-sdk-android/blob/master/mobilertc-android-studio/sample/proguard.cfg

**Comment by kevinbayes** [comment]
Thanks this is useful information that has not made it into a readme yet.

**Comment by ryosuji** [comment]
> Add guards, resolve this:
> https://github.com/zoom/zoom-sdk-android/blob/master/mobilertc-android-studio/sample/proguard.cfg

404 :(

see below :
https://github.com/decodedhealth/flutter_zoom_plugin/issues/14
