### ISSUE TITLE
'flutter_zoom_plugin/flutter_zoom_plugin-Swift.h' file not found

### ISSUE THREAD

**Issue by ortal83cohen** [decodedhealth/flutter_zoom_plugin#18]
Can't build with Xcode Version 11.3.1.
I get 'flutter_zoom_plugin/flutter_zoom_plugin-Swift.h' file not found

**Comment by kevinbayes** [comment]
Hi @ortal83cohen ,

Thanks for the feedback, can you give us a little more information on the error. Flutter doctor and steps to reproduce. 

Note if you are running it on the simulator use master_dev branch and use flutter from the command line to run the app. We do not currently us xcode to run apps, but rather just the command line.
