### ISSUE TITLE
Create, Schedule Meetings

### ISSUE THREAD

**Issue by superbrains** [decodedhealth/flutter_zoom_plugin#19]
How can I create and schedule meetings with this plugin?

**Comment by kevinbayes** [comment]
@superbrains this is not currently available, our use case was to join meetings. We happy to accept contributions as the integration is done, just need to bring the plugin up to feature parity actual SDKs.

**Comment by shinriyo** [comment]
ah, this sample can join just someone's room?
can not create a room?

**Comment by kevinbayes** [comment]
@shinriyo that is correct, only join. No support for creating a meeting.
