### ISSUE TITLE
Failed to initialize Zoom SDK

### ISSUE THREAD

**Issue by elziny** [decodedhealth/flutter_zoom_plugin#20]
Hello bro.
I've problem I cant join meeting, I use "example" code but it show this error.
"Failed to initialize Zoom SDK"

I use SDK zoom app but I can't know it's ok or which type i must use, and I don't know from where I get domian and userId.

Can you explain for me more ?

Thanks bro.

**Comment by kevinbayes** [comment]
@elziny you need to:

1. Signup for  a zoom account
2. Create an application (https://marketplace.zoom.us/develop/create) to get SDK credentials.
3. Use them in the example app to test test the plugin.

**Comment by gfiury** [comment]
Hello guys, 

Awesome plugin!!!

I'm having the same error "Failed to Initialize Zoom SDK". I've already changed the MeetingWidget with my ApiKey and ApiSecret.

Replaced 
```
this.zoomOptions = new ZoomOptions(
      domain: "zoom.us",
      appKey: "<myapikey>",
      appSecret: "<myapisecret>",
    );
```

The ApiKey and ApiSecret are working because I'm using those on an API to create a new Meeting.

```
I/flutter (10951): Created the view
I/ZoomSDK (10951): setDomain, set Zoom domain as zoom.us
I/System.out(10951): Failed to initialize Zoom SDK
I/flutter (10951): initialized
```
Am I missing something?

Thanks

**Comment by gfiury** [comment]
Debugging, got the a INTERNAL ERROR CODE: 3023. This means "Your SDK key or secret is invalid".

The Key and Secret I have are OK, even print the values of both at the init function. 
Double check the values, with these I'm generating new calls by demand. 

I do not know what I'm doing wrong :/

**Comment by kevinbayes** [comment]
@gfiury What platform are you trying to login with?

**Comment by gfiury** [comment]
@kevinbayes tried with a device with v10 (Q) and the emulator of Android Studio with v8. Both cases the same error.
Attached is the pubspec lock file, I'm going to upload the logs later.
Thanks
[pubspec.zip](https://github.com/decodedhealth/flutter_zoom_plugin/files/4463917/pubspec.zip)

**Comment by kevinbayes** [comment]
I have upgraded the plugin and will merge to master as soon as it has been tested. There is an open pull request that you can test.

**Comment by gfiury** [comment]
Thanks @kevinbayes, I been investigating the cause and it was that you need specific SDK credentials to make it work. You can't use JWT credentials, so with the new SDK credentials works perfectly.

**Comment by youssef-99** [comment]
i have the same error how can I fix it?

**Comment by 1-poojapatil** [comment]
Give app name as xyz.zoom.us in zoom account and in the code mention domain as zoom.us 
This is How i resolve it,Thank you

**Comment by 1-poojapatil** [comment]
Or please check in zoom account which app type you have used
