### ISSUE TITLE
Flutter Zoom Plugin - Giving a Meeting Idle When Meeting is Active.

### ISSUE THREAD

**Issue by Dcam1710** [decodedhealth/flutter_zoom_plugin#21]
Hi Kevin,

I've been using your Zoom plugin in a project I've been working on for the past few months and it's been working fine over the past few days, I've been getting this error when trying to start a meeting.
"MEETING_STATUS_IDLE - No meeting is running"

I have the meeting active in another Zoom app outside of my application and it works when I'm using it from Zoom app to Zoom app but for some reason now it's not working using the plugin when it was before. 

Is there something else I need to be doing now that Zoom has updated somethings to get the plugin to work again?

Thanks,
DC

**Comment by kevinbayes** [comment]
@Dcam1710 thanks for reporting this. We are in the process of upgrading to the latest zoom sdk so will be sure to have a look at that when testing.

If you need the previous version you can roll back to tag 0.0.3 to see if you get the same behaviour as you did before.

**Comment by Dcam1710** [comment]
@kevinbayes Thanks for your response and the help, this resource has been really helpful.
I worked on using the rolled back to version 0.0.3 like suggested but getting a MobileRTC error...
"Got response from join: MobileRTCMeetError(rawValue: 0)" error when trying to connect to an active meeting. If you don't have a solution to this issue yet, do you know about how long upgrading the current plugin to the latest SDK might take you? I may dive in on it as well.

**Comment by kevinbayes** [comment]
@Dcam1710 Ill have a look into this late next week.

**Comment by kevinbayes** [comment]
@Dcam1710 we have started to test the upgrade. The new Zoom SDK is larger than the previous so emulator testing will not be upgraded.
