### ISSUE TITLE
How to Enable Custom Meeting UI for  flutter_zoom_plugin

### ISSUE THREAD

**Issue by ramsubramani** [decodedhealth/flutter_zoom_plugin#23]
How to Enable Custom Meeting UI for  flutter_zoom_plugin? ...Is it possible? if possible can you tell me here step be stepl ...Thank you

**Comment by kevinbayes** [comment]
@ramsubramani no its not possible, you would need to modify the underlying zoom sdk assets directly. We are working on a command line to install the zoom sdk from a custom location. So that will help your usecase.

**Comment by ramsubramani** [comment]
Hi @kevinbayes , I am sorry if my question is not clear. Let me put it straight here, can we resize the zoom meeting screen layout (From full screen to half screen)? does zoom sdk support this for flutter?
