### ISSUE TITLE
sound problem

### ISSUE THREAD

**Issue by shinriyo** [decodedhealth/flutter_zoom_plugin#24]
Can it play sound?

**Comment by kevinbayes** [comment]
Yes, its just a wrapper around the zoom sdk.

**Comment by shinriyo** [comment]
@kevinbayes 
Yes. but it disabled the microphone.
I guess it should turn on the microphone.

**Comment by kevinbayes** [comment]
@shinriyo ah right, in the upgrade zoom branch I have added support to enable audio on join using the 'noDisconnectAudio' parameter as true.
