### ISSUE TITLE
Bringing down Android minSDKVersion

### ISSUE THREAD

**Issue by mikylucky** [decodedhealth/flutter_zoom_plugin#25]
Hi,
the package uses an Android minSDKVersion of 24, but the Android Zoom SDK uses 14.

Is there any specific reason why it has been brought up to 24?

**Comment by mikylucky** [comment]
I've noticed you already replied here #6 

Should I work on a pull request lowering the minSDKVersion?

**Comment by kevinbayes** [comment]
Sure, we are currently working on upgrading to the latest zoom. This will be merged into master next week, so we can lower it as part of that.

**Comment by kevinbayes** [comment]
@mikylucky we moving it down to 21 which is inline with the latest zoom android sdk.
