### ISSUE TITLE
How to resize the zoom meeting screen layout for flutter_zoom_plugin

### ISSUE THREAD

**Issue by Mohamed-Aswath** [decodedhealth/flutter_zoom_plugin#26]
Hi decodedhealth
Let me put it straight here, can we resize the zoom meeting screen layout (From full screen to half screen)? does zoom sdk support this for flutter?

**Comment by kevinbayes** [comment]
@Mohamed-Aswath sorry, currently we have not looked into doing this or even looked into if it is supported by the native sdks.
