### ISSUE TITLE
Meeting is invalid

### ISSUE THREAD

**Issue by suriyaKalidoss123** [decodedhealth/flutter_zoom_plugin#29]
When I run your app, After entering the meeting id and password. Alert box shows the meeting is invalid.

**Comment by DzungTNgo** [comment]
Hi,

Could you give us more information, such as the running platform, flutter doctor, what was your input and step to reproduce it.

Make sure that you have an active meeting and no space in the meeting id.

**Comment by suriyaKalidoss123** [comment]
Flutter Doctor Version:
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.19041.207], locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.      
[√] Android Studio (version 3.6)
[√] VS Code (version 1.44.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

MyMeeting id and password:
 MeetingWidget(
              meetingId: 'tyrfhkffjftvjh', meetingPassword: '126378382');

**Comment by DzungTNgo** [comment]
The meeting id and password you are using there are not valid Zoom meeting id nor password. They are just some random strings. Please look at Zoom instruction son how to use Zoom. create Zoom meetings and join a meeting
