### ISSUE TITLE
After pressing join button,Still it is showing preparing meeting

### ISSUE THREAD

**Issue by suriyaKalidoss123** [decodedhealth/flutter_zoom_plugin#31]
**Flutter Doctor Version:**
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.19041.207], locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.      
[√] Android Studio (version 3.6)
[√] VS Code (version 1.44.2)
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Steps to reproduce:**
After I press the join  button in the sample,
**The ui waits in preparing meeting**
![image](https://user-images.githubusercontent.com/45841845/80864629-7cd24600-8ca1-11ea-922b-833f84f3fef7.png)

**Comment by kevinbayes** [comment]
Hi @suriyaKalidoss123 
From the logs it seems like you are not entering a valid meeting id.

Steps to join a meeting are as follows:
1. Start a zoom meeting with the zoom app. 
2. Copy the meeting id and the password from the meeting invite.
3. Start the example application
4. Using the meeting id and password you copied from the zoom meeting enter those into the meeting id and password fields and click join. This plugin will not start a meeting but rather only join existing meetings.

**Comment by suriyaKalidoss123** [comment]
@kevinbayes  sorry the logs does not belong to the issue, I had done exactly what you said above, Then only this issue arises

**Comment by kevinbayes** [comment]
@suriyaKalidoss123 can you post the relevant logs please.

**Comment by suriyaKalidoss123** [comment]
issue resolved, When tested in different devices.
