### ISSUE TITLE
Unable to build the sample

### ISSUE THREAD

**Issue by suriyaKalidoss123** [decodedhealth/flutter_zoom_plugin#33]
## Your Environment
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.19041.207], locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/setup/#android-setup for detailed instructions.
[√] Android Studio (version 3.6)
[√] VS Code (version 1.44.2)
[√] Connected device (1 available)  

! Doctor found issues in 1 category.

## Expected Behavior
The sample should build normally

## Actual Behavior
Sample not builds properlly

## Steps to Reproduce

1.Run the attached sample
2.Unable to build the sample due to below issues

## Context
 I tried to create a sample using the below documentation:https://github.com/decodedhealth/flutter_zoom_plugin
But After sample creation unable to build sample. 
See below logs for details
**Attached Sample**
Sample :[zoom_sdk.zip]
[zoom_sdk.zip](https://github.com/decodedhealth/flutter_zoom_plugin/files/4579716/zoom_sdk.zip)

## Debug logs
Launching lib\main.dart on SM A605G in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > Android resource linking failed
     C:\Users\SURIYA\.gradle\caches\transforms-2\files-2.1\44c1808569e149a4997999b6407e61e7\commonlib\res\values\values.xml:233:5-238:13: AAPT: error: style attribute 'attr/colorPrimary (aka com.example.zoom_sdk:attr/colorPrimary)' not found.

     C:\Users\SURIYA\.gradle\caches\transforms-2\files-2.1\44c1808569e149a4997999b6407e61e7\commonlib\res\values\values.xml:233:5-238:13: AAPT: error: style attribute 'attr/colorPrimaryDark (aka com.example.zoom_sdk:attr/colorPrimaryDark)' not found.

     C:\Users\SURIYA\.gradle\caches\transforms-2\files-2.1\44c1808569e149a4997999b6407e61e7\commonlib\res\values\values.xml:233:5-238:13: AAPT: error: style attribute 'attr/colorAccent (aka com.example.zoom_sdk:attr/colorAccent)' not found.
     C:\Users\SURIYA\.gradle\caches\transforms-2\files-2.1\44c1808569e149a4997999b6407e61e7\commonlib\res\values\values.xml:233:5-238:13: AAPT: error: style attribute 'attr/toolbarStyle (aka com.example.zoom_sdk:attr/toolbarStyle)' not found.

     C:\Users\SURIYA\.gradle\caches\transforms-2\files-2.1\44c1808569e149a4997999b6407e61e7\commonlib\res\values\values.xml:239:5-241:13: AAPT: error: style attribute 'attr/contentInsetStart (aka com.example.zoom_sdk:attr/contentInsetStart)' not found.

     C:\Users\SURIYA\.gradle\caches\transforms-2\files-2.1\508defc37858ca983161bcac6af8069d\jetified-mobilertc\res\values\values.xml:3554:5-3558:10: AAPT: error: style attribute 'attr/textAllCaps (aka com.example.zoom_sdk:attr/textAllCaps)' not found.

     C:\Users\SURIYA\.gradle\caches\transforms-2\files-2.1\44c1808569e149a4997999b6407e61e7\commonlib\res\values\values.xml:971:5-974:10: AAPT: error: style attribute 'attr/windowActionBar (aka com.example.zoom_sdk:attr/windowActionBar)' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 53s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin flutter_zoom_plugin...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'flutter_zoom_plugin'.
> SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at 'D:\software\flutter\.pub-cache\git\flutter_zoom_plugin-46fb61bcbd4d0116d9f4a40855c3e4ca9434636c\android\local.properties'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s
The plugin flutter_zoom_plugin could not be built due to the issue above.
Exited (sigterm)

**Comment by suriyaKalidoss123** [comment]
This issue occurs also in 0.0.5 version
  flutter_zoom_plugin:
    git:
      url: git://github.com/decodedhealth/flutter_zoom_plugin.git
      ref: 0.0.5

**Comment by suriyaKalidoss123** [comment]
IN 0.0.4 version this issue occurs

flutter_zoom_plugin:
    git:
      url: git://github.com/decodedhealth/flutter_zoom_plugin.git
      ref: 0.0.4

Launching lib\main.dart on SM A605G in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_zoom_plugin:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'res/drawable/zm_next_arrow.xml'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 32s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)

**Comment by suriyaKalidoss123** [comment]
@kevinbayes  Please help me resolve this issues

**Comment by suriyaKalidoss123** [comment]
@kevinbayes, please guide

**Comment by kevinbayes** [comment]
@suriyaKalidoss123 sorry for the delay I will look at your example early next week.

**Comment by kevinbayes** [comment]
@suriyaKalidoss123 we will be pushing out an update to fix this.

**Comment by suriyaKalidoss123** [comment]
thanks

**Comment by kevinbayes** [comment]
@suriyaKalidoss123 please try the new version in your uploaded sample:

Add to pubspec.yaml

```
  flutter_zoom_plugin:
    git:
      url: git://github.com/decodedhealth/flutter_zoom_plugin.git
      ref: 0.0.7
```

add to app/build.gradle dependencies:

```
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.android.material:material:1.0.0'
```

**Comment by suriyaKalidoss123** [comment]
Thanks for effort,But issue still exist.
Here is the log:
Launching lib\main.dart on SM A605G in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_zoom_plugin:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'res/drawable/zm_next_arrow.xml'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 46s
Gradle task assembleDebug failed with exit code 1
Exited (sigterm)


Build.gradle:
android {
    compileSdkVersion 29

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId "com.example.zoom_sdk"
        minSdkVersion 24
        targetSdkVersion 29
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
             signingConfig signingConfigs.debug
             minifyEnabled true
             useProguard true

             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro' 
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test:runner:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.1'
    implementation 'androidx.appcompat:appcompat:1.0.2'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    implementation 'com.google.android.material:material:1.0.0'

}

**Comment by DzungTNgo** [comment]
Hi, 

I can see that you have added the dependencies to the `build.gradle` file.
Just to be sure, did you update the zoom plugin to `0.0.7` in the `pubspec.yaml` file? Also run `flutter clean` and `flutter pub get` before building your app again.

**Comment by suriyaKalidoss123** [comment]
@DzungTNgo  added code to app/build.gradle,
Updated to 0.0.7 in YAML,clean,run done
But the issue exists.
Logs:
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter_zoom_plugin:mergeDebugJavaResource'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > More than one file was found with OS independent path 'res/drawable/zm_next_arrow.xml'

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by suriyaKalidoss123** [comment]
[zoom_sdk (2).zip](https://github.com/decodedhealth/flutter_zoom_plugin/files/4605072/zoom_sdk.2.zip)
**Reattached the sample:**

**Comment by DzungTNgo** [comment]
Please change to `classpath 'com.android.tools.build:gradle:3.4.2'` in `android/build.gradle` and try again.
I have seen some reported issues with fluttter using verison 3.5.0.

**Comment by kevinbayes** [comment]
@suriyaKalidoss123 were you able to get this working?

**Comment by javieralcantara** [comment]
Any solutions..?

**Comment by suriyaKalidoss123** [comment]
3.4.2 works fine issue resolved.I have Another question How to create the meeting in your sample?

**Comment by kevinbayes** [comment]
@suriyaKalidoss123 we do not support creating meeting yet, just joining. Add it as a feature request and we can have a look at it when we have time. Or we welcome pull requests.

**Comment by evilmtv** [comment]
> Please change to `classpath 'com.android.tools.build:gradle:3.4.2'` in `android/build.gradle` and try again.
> I have seen some reported issues with fluttter using verison 3.5.0.

This worked for me, thank you.

**Comment by izaiasemjr** [comment]
Hi, Someone have some feelings why the package not work using the more recent gradle (3.5.0)?

**Comment by kevinbayes** [comment]
Yeah the packaging just needs to be fixed. Once that is done the upgrade can be done. We are just a bit slammed at the moment so cannot get around to doing it. We can review a pull request if needed.

**Comment by izaiasemjr** [comment]
Thanks @kevinbayes for answer me.  Would have some  directions to solve this problem?
