### ISSUE TITLE
It is showing More than one file was found with OS independent path 'res/drawable/zm_next_arrow.xml after debugging

### ISSUE THREAD

**Issue by LucasFancation** [decodedhealth/flutter_zoom_plugin#35]
## Your Environment
* Plugin version:
* Platform: Android
* OS version: Android API 28
* Device manufacturer / model: Android Emulator
* Flutter info (`flutter doctor`):
* Plugin config: 
flutter_zoom_plugin:
    git:
      url: git://github.com/decodedhealth/flutter_zoom_plugin.git
      ref: master
```dart <-- Syntax highlighting: DO NOT REMOVE -->
FAILURE: Build failed with an exception.
[   +3 ms] * What went wrong:
[   +1 ms] Execution failed for task ':flutter_zoom_plugin:mergeDebugJavaResource'.
[   +2 ms] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[   +1 ms]    > More than one file was found with OS independent path 'res/drawable/zm_next_arrow.xml'
```

## Expected Behavior
I want to be able to debug in my emulator

## Actual Behavior
It is showing this error

## Steps to Reproduce

1. Enter the dependency in pubspec.yaml
2. Change the minsdk to 21
3. Add the zoom proguard.cfg
4. flutter run -v

## Context
The thing I want to do is just making it abe to debug

## Debug logs

<details>
	<summary>Logs</summary>

``` <!-- syntax-highligting:  DO NOT REMOVE -->
[   +4 ms] FAILURE: Build failed with an exception.
[   +3 ms] * What went wrong:
[   +1 ms] Execution failed for task ':flutter_zoom_plugin:mergeDebugJavaResource'.
[   +2 ms] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[   +1 ms]    > More than one file was found with OS independent path 'res/drawable/zm_next_arrow.xml'
[   +1 ms] * Try:
[   +1 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full     
insights.
[   +1 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 2m 16s
```

</details>

**Comment by kevinbayes** [comment]
@LucasFancation we will be pushing an update out to fix this.

**Comment by kevinbayes** [comment]
Okay try tag 0.0.7

**Comment by LucasFancation** [comment]
Okay thanks Kevin, it works.
