### ISSUE TITLE
Please Add Start Call Feature

### ISSUE THREAD

**Issue by sudip92** [decodedhealth/flutter_zoom_plugin#47]
In this current plugin, we can only join an ongoing call. Is there any way to start a meeting as host in this current version.

**Comment by DzungTNgo** [comment]
Thanks for the interest. We have a PR currently for starting call with non-login user. It is being reviewed in the next couple of days.

We also have a ticket for implementing the login user flow. It will get implemented when we have time. Of course, any PR and contributions are welcomed.
