### ISSUE TITLE
Meeting Password dialog appears even the password is set on the ZoomMeetingOptions

### ISSUE THREAD

**Issue by selvesandev** [decodedhealth/flutter_zoom_plugin#49]
The start meeting widget is asking for a meeting password even when i provided the password in the `ZoomMeetingOptoins`

* Platform: iOS or Android

```dart <-- Syntax highlighting: DO NOT REMOVE -->
class StartMeetingWidget extends StatelessWidget {
  ZoomOptions zoomOptions;
  ZoomMeetingOptions meetingOptions;

  Timer timer;

  StartMeetingWidget({Key key, meetingId, meetingPassword}) : super(key: key) {
    print(meetingPassword);
    this.zoomOptions = new ZoomOptions(
      domain: "zoom.us",
      appKey: "key",
      appSecret: "secret",
    );
    this.meetingOptions = new ZoomMeetingOptions(
        userId: 'user_id',
        displayName: 'Selvesan',
        meetingPassword: meetingPassword,
        meetingId: meetingId,
        zoomAccessToken:"Access token"
        zoomToken: "token",
        disableDialIn: "true",
        disableDrive: "true",
        disableInvite: "true",
        disableShare: "true",
        noAudio: "false",
        noDisconnectAudio: "false");
    print(this.meetingOptions.meetingPassword);
  }
}
```

## Expected Behavior
The meeting password dialog should not pop up. The dialog box does not appear while using the `MeetingWidget`. Shouldn't it be same for the `StartMeetingWidget` as well

**Comment by selvesandev** [comment]
Sorry there was wrong ZAK being used, closing this for now. Thank you to the contributors for doing such a awesome work. Please keep updating this

**Comment by azackmatoff** [comment]
So, I’m having the same issue, it worked couple times to start meeting, but now it’s asking for a password to start meeting, a pop up is appearing, i enter password, it’s taking to a waiting room of zoom and not starting anything. 
What to do next?
