### ISSUE TITLE
Can't start video on iphone simulator

### ISSUE THREAD

**Issue by shaharsol** [decodedhealth/flutter_zoom_plugin#5]
While can't get it to work on Android #4 , It did partly work on iOS. It just won't let me start the video. Clicking the button changes nothing. Should I config something? Maybe the simulator needs special permissions?

<img width="454" alt="Screen Shot 2019-11-03 at 12 42 48" src="https://user-images.githubusercontent.com/672778/68084065-59852600-fe39-11e9-8a4b-bd02bf29a349.png">

**Comment by kevinbayes** [comment]
iOS emulator camera does not seem to work, do real device testing to test this out.
