### ISSUE TITLE
Handle navigation on LeaveMeeting

### ISSUE THREAD

**Issue by shaharsol** [decodedhealth/flutter_zoom_plugin#8]
What do I do to respond to the event when the user clicked "Leave meeting" inside the zoom chat? or otherwise when the chat is closed?

**Comment by kevinbayes** [comment]
Good question, so the event stream for the status has not been done yet. So as soon as that becomes available it will be a lot easier. Currently, though you need to poll for the meeting status, but it seems the status from the iOS sdk is not consistent with android. So in saying that, I would recommend having a page that is 'under' or shadows the meeting. Then page will be show when the meeting has ended.

I am busy with a code example, but will take a couple of days to get done, as I am working on pushing some Decoded Health systems out.
